excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods


  #Rules
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - todo
  - variable_name
  - vertical_whitespace

 