excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods


#Rules
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - todo
  - variable_name
  - vertical_whitespace
  - force_cast

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length: 140

# or they can set both explicitly
file_length:
  warning: 400
  error: 500
 